### ISSUE TITLE
missing calc_lfp method?

### ISSUE THREAD

**Issue by cjayb** [solveignaess/EEG#1]
After installing `LFPy` via the `conda-forge`-method ([as per README](https://github.com/LFPy/LFPy)), I get the error below when trying to run the examples. Where is the `calc_lfp`-method supposed to be coming from, I wonder?

```python
python make_data_figure2.py
~/miniconda3/envs/lfpy_conda/lib/python3.8/site-packages/LFPy/cell.py:1051: UserWarning: Cell.simulate parameter rec_current_dipole_moment is deprecated.
  warn('Cell.simulate parameter {} is deprecated.'.format(key))
Traceback (most recent call last):
  File "make_data_figure2.py", line 171, in <module>
    cell, cb_LFP_close, cb_LFP_far, multi_dip_LFP_close, multi_dip_LFP_far, db_LFP_close, db_LFP_far, LFP_max, time_max, multi_dips, multi_dip_locs, single_dip, r_mid, X, Z, X_far, Z_far = make_data(morphology, syninds, x_rot=xrot, y_rot=yrot)
  File "make_data_figure2.py", line 23, in make_data
    cell, synapse, grid_electrode = simulate(cell_parameters, synapse_parameters, grid_electrode_parameters, syninds, x_rot=x_rot, y_rot=y_rot, z_rot=z_rot, active=active)
  File "make_data_figure2.py", line 159, in simulate
    grid_electrode.calc_lfp()
AttributeError: 'RecExtElectrode' object has no attribute 'calc_lfp'
```

Really enjoyed the NI-paper, by the way, congrats!

My troubles could be related to a botched installation of `LFPy`, reported here: https://github.com/LFPy/LFPy/issues/319

**Comment by espenhgn** [comment]
Hi - for future reference, the `RecExtElectrode.calc_lfp` method was removed in LFPy-2.2 due to the incorporation of LFPykit (LFPy.readthedocs.io). We had to change some LFPy syntax for this. Either downgrade to LFPy-2.1.2 or update these codes like so:
```
import LFPy
...
cell = LFPy.Cell(**kwargs)
....
electrode = LFPy.RecExtElectrode(cell=cell, **kwargs)  # or some other lfpykit.models class wrapped by LFPy-2.2
cell.simulate(rec_imem=True)
Ve = electrode.get_transformation_matrix() @ cell.imem
```
in order to compute the extracellular potential

**Comment by cjayb** [comment]
Cool, thanks. Figure 2 created OK with `lfpy=2.1`, submitted PR on bug for Fig 3, although I can see I'm going to need a Bigger Computer to run that one ;)

**Comment by torbjone** [comment]
Hi,
great that you got this running. 

Just a comment with regards to the Bigger Computer: Fig 3 does indeed take a lot of time to make. During the validation of the single-dipole approximation, we need to make a large number of dipoles that are sent through the four-sphere head model. But after it has been confirmed that you can use the single-dipole approximation, it is orders of magnitude faster :-)
