### ISSUE TITLE
Fail to run multi-compartment simulation with mpi

### ISSUE THREAD

**Issue by HilbertHuangHitomi** [solveignaess/EEG#6]
Hello there~
I would like to reuse `hybrid_EEG_evoked` to simulate. It works well during the LIF network simulation and processing the raw nest output, but fails to simulate the multi-compartment models.

Here is my scheme.
1. create an environment with `conda create --name neuro python=3.8`
2. install necessary packages `LFPy==2.1.2`, `neuron==7.8.1`, `hybridLFPy==0.1.4 `
3. compile mod mechanisms with `nrnivmodl`
4. run the simulation with `mpiexec python hybrid_sim_evoked_with_EEG.py`

The LIF network simulation works well and gives expected results to evoked_cdm/raw_nest_output/. 
As for the multi-compartment simulation, it also gives completed results to evoked_cdm/processed_nest_output/.

However, after reporting `population initialized in X seconds`, it raises Segmentation fault as

> [SERVER:02380] *** Process received signal ***
> [SERVER:02380] Signal: Segmentation fault (11)
> [SERVER:02380] Signal code: Address not mapped (1)
> [SERVER:02380] Failing at address: 0x8
> [SERVER:02380] [ 0] /lib/x86_64-linux-gnu/libpthread.so.0(+0x11390)[0x7fe2a75b9390]
> [SERVER:02380] [ 1] /user/miniconda3/envs/neuro/lib/python3.8/site-packages/neuron/.data/lib/libnrniv.so(_ZN8NetCvode11init_eventsEv+0x1eb)[0x7fe2232810eb]
> [SERVER:02380] [ 2] /user/miniconda3/envs/neuro/lib/python3.8/site-packages/neuron/.data/lib/libnrniv.so(nrn_finitialize+0x3f5)[0x7fe2232d98e5]
> [SERVER:02380] [ 3] /user/miniconda3/envs/neuro/lib/python3.8/site-packages/neuron/.data/lib/libnrniv.so(finitialize+0x3a)[0x7fe2232d9aea]
> [SERVER:02380] [ 4] /user/miniconda3/envs/neuro/lib/python3.8/site-packages/neuron/.data/lib/libnrniv.so(hoc_call+0x18e)[0x7fe2232d505e]
> [SERVER:02380] [ 5] /user/miniconda3/envs/neuro/lib/python3.8/site-packages/neuron/.data/lib/libnrnpython3.so(+0x13ff8)[0x7fe222defff8]
> [SERVER:02380] [ 6] /user/miniconda3/envs/neuro/lib/python3.8/site-packages/neuron/.data/lib/libnrniv.so(_ZN10OcJumpImpl7fpycallEPFPvS0_S0_ES0_S0_+0x3e)[0x7fe2232a82ee]
> [SERVER:02380] [ 7] /user/miniconda3/envs/neuro/lib/python3.8/site-packages/neuron/.data/lib/libnrnpython3.so(+0x1418e)[0x7fe222df018e]
> [SERVER:02380] [ 8] python(_PyObject_MakeTpCall+0x31e)[0x55a826c95f2e]
> [SERVER:02380] [ 9] python(_PyEval_EvalFrameDefault+0x534b)[0x55a826d2ff6b]
> [SERVER:02380] [10] python(_PyEval_EvalCodeWithName+0x2c3)[0x55a826d0b503]
> [SERVER:02380] [11] python(_PyFunction_Vectorcall+0x378)[0x55a826d0c8d8]
> [SERVER:02380] [12] python(+0x1b32a7)[0x55a826d0e2a7]
> [SERVER:02380] [13] python(+0x124fba)[0x55a826c7ffba]
> [SERVER:02380] [14] python(PyObject_Call+0x255)[0x55a826c802b5]
> [SERVER:02380] [15] python(_PyEval_EvalFrameDefault+0x21c1)[0x55a826d2cde1]
> [SERVER:02380] [16] python(_PyEval_EvalCodeWithName+0x2c3)[0x55a826d0b503]
> [SERVER:02380] [17] python(_PyFunction_Vectorcall+0x378)[0x55a826d0c8d8]
> [SERVER:02380] [18] python(_PyEval_EvalFrameDefault+0xa4b)[0x55a826d2b66b]
> [SERVER:02380] [19] python(_PyFunction_Vectorcall+0x1a6)[0x55a826d0c706]
> [SERVER:02380] [20] python(_PyEval_EvalFrameDefault+0xa4b)[0x55a826d2b66b]
> [SERVER:02380] [21] python(_PyEval_EvalCodeWithName+0x2c3)[0x55a826d0b503]
> [SERVER:02380] [22] python(PyEval_EvalCodeEx+0x39)[0x55a826d0c559]
> [SERVER:02380] [23] python(PyEval_EvalCode+0x1b)[0x55a826daf9ab]
> [SERVER:02380] [24] python(+0x254a43)[0x55a826dafa43]
> [SERVER:02380] [25] python(+0x26e6b3)[0x55a826dc96b3]
> [SERVER:02380] [26] python(+0x2735b2)[0x55a826dce5b2]
> [SERVER:02380] [27] python(PyRun_SimpleFileExFlags+0x1b2)[0x55a826dce792]
> [SERVER:02380] [28] python(Py_RunMain+0x36d)[0x55a826dced0d]
> [SERVER:02380] [29] python(Py_BytesMain+0x39)[0x55a826dceec9]
> [SERVER:02380] *** End of error message ***
> --------------------------------------------------------------------------
> Primary job  terminated normally, but 1 process returned
> a non-zero exit code. Per user-direction, the job has been aborted.
> --------------------------------------------------------------------------
> --------------------------------------------------------------------------
> mpiexec noticed that process rank 14 with PID 0 on node SERVER exited on signal 11 (Segmentation fault).
> --------------------------------------------------------------------------

I have tried to fix this with install neuron 8.0a following [https://github.com/neuronsimulator/nrn/pull/1010](url), by downloading the wheel and running `pip install NEURON-8.0a0-cp38-cp38-manylinux1_x86_64.whl` in a new environment, but the error still rises.

Could you help me to solve it, please?

**Comment by torbjone** [comment]
Hi,
thank you for your interest in hybridLFPy and I hope we can help you to resolve this problem.
Since this is probably related to hybridLFPy and not specifically to the EEG calculation, could you perhaps open this issue at the hybridLFPy page instead?:
https://github.com/INM-6/hybridLFPy/issues 

Thank you!

**Comment by HilbertHuangHitomi** [comment]
open in [https://github.com/INM-6/hybridLFPy/issues/41](url)
